server:  port: 8021

spring:  jackson.serialization:    INDENT_OUTPUT : true    WRITE_DATES_AS_TIMESTAMPS : false
  datasource:
    url: jdbc:sqlserver://MARCOS;databaseName=DBCINEWEB    username: marquitos    password: marquitos    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver 
  jpa:    show-sql: false    properties:      hibernate:        enable_lazy_load_no_trans: true    